#!/usr/bin/env python3
"""Generate docs/data.json for the landing page (docs/index.html).

Scans raw/ and git history so the landing page's knowledge graph, tag list,
最新更新 list, and stat counters stay in sync with the repository without
manual edits. docs/index.html fetches data.json at load time; the GitHub API
remains a live overlay for contributor names and merged-PR counts.

Data sources:
    - raw/ directory tree     → categories, tags, knowledge-graph tree, skill count
    - git rev-list            → commit count
    - README ## 📰 最近更新    → updates list (top entries, links stripped)
    - optional --github-stats → contributors / mergedPRs fetched by the
                                GitHub Action via `gh api` (null when run locally)

Usage:
    python scripts/update_landing_page.py [--github-stats path/to/gh-stats.json]

Output is deterministic for a given commit (no wall-clock timestamps), so the
GitHub Action only commits when content actually changed.
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "raw"
README = ROOT / "README.md"
OUT = ROOT / "docs" / "data.json"

MAX_UPDATES = 8

CJK_RE = re.compile(r"[㐀-鿿]")


def has_cjk(s):
    return bool(CJK_RE.search(s))


def git(*args):
    return subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, text=True, encoding="utf-8"
    ).stdout.strip()


def skill_label(skill_md, sub):
    """Display label for a SKILL.md: the Chinese topic dir when one exists, else the slug."""
    d = skill_md.parent
    if has_cjk(d.name):
        return d.name
    if d.parent != sub and has_cjk(d.parent.name):
        return d.parent.name
    return d.name


def build_tree():
    """raw/ → [{name, children: [{name, skills: [...]}]}] for the knowledge-graph canvas."""
    tree = []
    for cat in sorted(p for p in RAW.iterdir() if p.is_dir()):
        children = []
        for sub in sorted(p for p in cat.iterdir() if p.is_dir()):
            labels = []
            for skill_md in sorted(sub.rglob("SKILL.md")):
                label = skill_label(skill_md, sub)
                if label not in labels:
                    labels.append(label)
            if labels:
                children.append({"name": sub.name, "skills": labels})
        tree.append({"name": cat.name, "children": children})
    return tree


def parse_updates():
    """Top entries of README ## 📰 最近更新, PR link/author suffix stripped."""
    if not README.exists():
        return []
    updates = []
    in_section = False
    for line in README.read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            in_section = "最近更新" in line
            continue
        if not in_section:
            continue
        m = re.match(r"-\s+\*\*(\d{4}-\d{2}-\d{2})\*\*\s+(.*)", line.strip())
        if not m:
            continue
        date, text = m.group(1), m.group(2)
        # strip trailing "([#N](url) by @author)"
        text = re.sub(r"\s*\(\[#\d+\]\([^)]*\)[^()]*\)\s*$", "", text)
        # flatten any remaining markdown links
        text = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text).strip()
        updates.append({"date": date, "text": text})
        if len(updates) >= MAX_UPDATES:
            break
    return updates


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--github-stats", help="JSON file with {contributors, mergedPRs} from gh api")
    args = ap.parse_args()

    gh = {}
    if args.github_stats:
        try:
            gh = json.loads(Path(args.github_stats).read_text(encoding="utf-8"))
        except (OSError, ValueError) as e:
            print(f"warn: cannot read --github-stats: {e}", file=sys.stderr)

    tree = build_tree()
    skills = len(list(RAW.rglob("SKILL.md")))
    contributors = gh.get("contributors") or None

    data = {
        "_comment": "AUTO-GENERATED by scripts/update_landing_page.py — do not edit by hand",
        "generated": git("log", "-1", "--format=%cs"),
        "stats": {
            "commits": int(git("rev-list", "--count", "HEAD") or 0),
            "categories": len(tree),
            "skills": skills,
            "contributors": len(contributors) if contributors else None,
            "mergedPRs": gh.get("mergedPRs"),
        },
        "contributors": contributors,
        "tags": [cat["name"] for cat in tree],
        "updates": parse_updates(),
        "tree": tree,
    }

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
    print(
        f"docs/data.json updated: {data['stats']['commits']} commits, "
        f"{len(tree)} categories, {skills} skills, {len(data['updates'])} updates"
    )


if __name__ == "__main__":
    main()
